name: amd64_windows_gcc

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  amd64_windows:
    runs-on: windows-2019
    strategy:
      matrix:
        compiler: [gcc, clang]
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
    - run: pacman --noconfirm -S make gcc
      if: ${{ matrix.compiler == 'gcc' }}
    - run: pacman --noconfirm -S make mingw-w64-x86_64-clang
      if: ${{ matrix.compiler == 'clang' }}
    - run: ${{ matrix.compiler }} --version
    - run: ${{ matrix.compiler }} y6_decrypt.exe
    - run: ${{ matrix.compiler }} y6_encrypt.exe
    - run: ${{ matrix.compiler }} je_decrypt.exe
    - run: ${{ matrix.compiler }} je_encrypt.exe
    - run: ${{ matrix.compiler }} lj_decrypt.exe
    - run: ${{ matrix.compiler }} lj_encrypt.exe
